enum ModType {
  LAVA = 'LAVA',
  LIGHTNING = 'LIGHTNING',
  PLASMA = 'PLASMA',
  ROCKET = 'ROCKET',
  ROCKET_SPLASH = 'ROCKET_SPLASH',
  SLIME = 'SLIME',
  SWITCHTEAM = 'SWITCHTEAM'
}

export default ModType