enum PowerUpType {
  ARMOR_REGEN = 'ARMOR_REGEN',
  BATTLESUIT = 'BATTLESUIT',
  DOUBLER = 'DOUBLER',
  FLIGHT = 'FLIGHT',
  GUARD = 'GUARD',
  HASTE = 'HASTE',
  INVIS = 'INVIS',
  INVULNERABILITY = 'INVULNERABILITY',
  OTHER_POWERUP = 'OTHER_POWERUP',
  QUAD = 'QUAD',
  REGEN = 'REGEN'
}

export default PowerUpType