enum MedalType {
  ACCURACY = 'ACCURACY',
  ASSISTS = 'ASSISTS',
  CAPTURES = 'CAPTURES',
  COMBOKILL = 'COMBOKILL',
  DEFENDS = 'DEFENDS',
  EXCELLENT = 'EXCELLENT',
  FIRSTFRAGE = 'FIRSTFRAG',
  HEADSHOT = 'HEADSHOT',
  HUMILIATION = 'HUMILIATION',
  IMPRESSIVE = 'IMPRESSIVE',
  MIDAIR = 'MIDAIR',
  PERFECT = 'PERFECT',
  PERFORATED = 'PERFORATED',
  QUADGOD = 'QUADGOD',
  RAMPAGE = 'RAMPAGE',
  REVENGE = 'REVENGE'
}

export default MedalType