enum WeaponType {
  BFG = 'BFG',
  CHAINGUN = 'CHAINGUN',
  GAUNTLET = 'GAUNTLET',
  GRENADE = 'GRENADE',
  HMG = 'HMG',
  LIGHTNING = 'LIGHTNING',
  MACHINEGUN = 'MACHINEGUN',
  NAILGUN = 'NAILGUN',
  OTHER_WEAPON = 'OTHER_WEAPON',
  PLASMA = 'PLASMA',
  PROXMINE = 'PROXMINE',
  RAILGUN = 'RAILGUN',
  ROCKET = 'ROCKET',
  SHOTGUN = 'SHOTGUN'
}

export default WeaponType